### ISSUE TITLE
Why flip x, translation, and z?

### ISSUE THREAD

**Issue by JzHuai0108** [zhangganlin/GlORIE-SLAM#10]
Dear authors,

Thank you for the open source effort. I am perusing the code and meet several unclear points.
Can you please clarify them?
1. why do we negate x and z in [here](https://github.com/zhangganlin/GlORIE-SLAM/blob/7f96e5e6e5d2c3411712a7ffebb00fe2e5a24c92/src/neural_point.py#L477-#L485)?
2. why do we negate translation [here](https://github.com/zhangganlin/GlORIE-SLAM/blob/7f96e5e6e5d2c3411712a7ffebb00fe2e5a24c92/src/mapper.py#L213)?

**Comment by zhangganlin** [comment]
Hi,

The modifications to the signs are inherited from Point-SLAM and NICE-SLAM. Here is a clear explanation in Point-SLAM: https://github.com/eriksandstroem/Point-SLAM/blob/5bd918d70c10497d2369fd2e86bba792ea959d50/src/utils/datasets.py#L142C1-L146C88

Best,
Ganlin

**Comment by JzHuai0108** [comment]
Thank you for the heads-up. This comment clarifies somewhat. I am content with it.
