### ISSUE TITLE
About config on different datasets

### ISSUE THREAD

**Issue by Ysc-shark** [zhangganlin/GlORIE-SLAM#4]
Thank you for your excellent work.

I would like to try running your code on some different datasets for SLAM, such as outdoor scenes with 1920×1280 resolution input. Could you please advise on how to choose certain parameters in the config file for such cases? Any suggestions would be greatly appreciated. Thank you.

![image](https://github.com/user-attachments/assets/36b0f52c-419d-4114-80ba-1d11a69613af)
![image](https://github.com/user-attachments/assets/f0edb5e8-da6c-4486-97ed-138ea8cb5ec1)

**Comment by zhangganlin** [comment]
Hi,

Personally I did not try glorie-slam on other datasets, but if you want to test on some realworld datasets, it should be similar to ScanNet or TUM-RGBD. For outdoor dataset, I think you can set `tracking.motion_filter.thresh` and 'tracking.frontend.keyframe_thresh' a bit larger avoid adding too many keyframes.

Also, 1920*1080 might be too large to fit into memory, I suggest to downsample it first.

Best,
Ganlin

**Comment by Ysc-shark** [comment]
> Hi,
> 
> Personally I did not try glorie-slam on other datasets, but if you want to test on some realworld datasets, it should be similar to ScanNet or TUM-RGBD. For outdoor dataset, I think you can set `tracking.motion_filter.thresh` and 'tracking.frontend.keyframe_thresh' a bit larger avoid adding too many keyframes.
> 
> Also, 1920*1080 might be too large to fit into memory, I suggest to downsample it first.
> 
> Best, Ganlin

Thanks
