### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by Savior1s** [zhangganlin/GlORIE-SLAM#9]
Thx for your great work! And after I run the 'python run.py configs/Replica/room0.yaml ' and how could I visual my reconstruction results

**Comment by zhangganlin** [comment]
Hi, 
The reconstructed mesh can be generated through this function:
https://github.com/zhangganlin/GlORIE-SLAM/blob/7f96e5e6e5d2c3411712a7ffebb00fe2e5a24c92/src/slam.py#L160
After that, you can use open3d or other tools to visualize the generated `.ply` file
